db:
  image: postgres:15
  container_name: fuelsync-db
  restart: always
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: ${DB_USER}
    POSTGRES_PASSWORD: ${DB_PASSWORD}
    POSTGRES_DB: ${DB_NAME}
  volumes:
    - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
